### ISSUE TITLE
Suggestions: Lorebook, Actor State Agent

### ISSUE THREAD

**Issue by maxthraxx** [vegu-ai/talemate#43]
Great work, have been exploring Talemate and its produced some of the highest quality output for roleplay I've seen yet.

I had a couple suggestions:

1. Add a "Lorebook" feature. Am not sure if you are familiar with NovelAI, but a Lorebook is essentially a way to define specific "keywords" along with descriptions for each. Then, if that keyword is detected in the current context, the description gets inserted into the AI context. Its a way to insert custom tailored descriptions of people, places, things, concepts for the AI to take into account. I suppose entries could also be just added to the long-term memory database, and not the AI context, though I'm not sure how effective that would be / how it would affect things. Interesting question. Read here for a more detailed rundown: https://docs.novelai.net/text/lorebook.html

2. Add an "Actor State" agent: similar to the World State agent, but it'd be for Actor states. You could add functionality to mark specific Actor detail fields to be checked and updated periodically. I'm thinking this could be used for many, many interesting things, but to name a few: 

- naturally updating Actor backstory as you talk to them (add a field called "Backstory", then the Actor agent would detect a mismatch between existing backstory content and what has been discussed/revealed in the current context, and naturally update the backstory with the new info)
- realistic Actor goal tracking (give all Actors a field like "Immediate Goals" and then have them act on it, likely in combination with a field like "Long-term Goals", so the immediate goals will align towards the long-term goals.)
- Actor-Player Relationship tracking (might require a separate system, but the idea being its a short history of all the interactions between the Player and an Actor, and the tone of the interaction, that results in a determination of their overall relationship status - here I don't mean romantic, per se, but for example: Friendly, Allied, Best Friends, Mentor, etc. which would have an effect on that Actor's reactions and responses to the Player.)

I have had ideas for a Questing system (based on: different Quest types, Quest staging based on quest type, Quest stakes, Quest objectives, etc.) but it is quite involved and I'm not sure how useful it really is. I may post it later if development on Talemate continues (I'm no coder unfortunately but I hope it will!)

Thanks and great work, hope these suggestions may be of interest.

**Comment by vegu-ai-tools** [comment]
Thanks for the feedback and suggestions!

These are all great and point towards something that is pretty high on my list to get right, which is accurate and consistent insertion of current truth.

In the end we want to be able insert relevant and current state information (be it world information, past events, current states, etc.,) into the context.

The "long term memory" agent name is probably a bit misleading, since it already serves to select/insert relevant information based on the context (not just actor "memories"), but talemate is currently missing the tools for us to inspect and manage the data directly.

The lorebook idea for example probably just needs a user interface for us to manage entries in the "memory". Might be a low hanging fruit thing for me to do soon.

Actor state agent makes total sense to me, and is something i will be working on while also doing an overhaul of the Director agent.

Will turn some of this stuff into separate tickets, and leave this ticket open until then.

**Comment by vegu-ai-tools** [comment]
Separated into individual tickets
